const CONFIG = {
    introTitle: 'Hellu Song Luân cụa em!',
    introDesc: `Giờ mình chơi 1 trò chơi nho nhỏ, nếu thua sẽ bị phạt nhá ^^`,
    btnIntro: 'Oki nuôn',
    title: 'Anh có iu em hong?',
    desc: 'Bắt buộc phải chọn mới tiếp tục đượt',
    btnYes: 'Chạ iu em',
    btnNo: 'Yêu em nhìu nắmm <3',
    question:'He he anh bắt buộc phải chọn cái nì đúng hong, đùa hoy chứ em bít anh yêu em nhìu mà. Bây giờ anh hãy viết 1 lý do vì sao anh yêu em ik!',
    btnReply: '',
    reply: 'Còn đây là lời em mún nói với anh...',
    mess: 'Happy Valentine anh iu cụa emmm <3',
    messDesc: 'Em yêu anh nhìu nắm, mong là chúng mình sẽ bên nhau thêm nhìu cái valentine nữa nhá hehe. Giờ thì ấn zô nút bên dưới để nêu cảm nghĩ của anh zề món quà này nhá ^^',
    btnAccept: 'Ấn zô đây nè',
    messLink: 'http://m.me/huonglinh.nguyen11' 
